services:
  postgres:
    image: postgres:14
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"  # optional, for inspecting from host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build: .
    container_name: airflow
    hostname: airflow
    ports:
      - "8080:8080"
    command: standalone
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    environment:
      - PYTHONPATH=/opt/airflow/dags
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # define MySQL project DB connection for DAGs
      - AIRFLOW_CONN_MYSQL_LOCAL=mysql+mysqlconnector://${MYAPP_DB_USER}:${MYAPP_DB_PASSWORD}@${MYAPP_DB_DOCKER_HOST}:${MYAPP_DB_PORT}/${MYAPP_DB_DATABASE}
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: