services:
  airflow:
    build: .
    container_name: airflow
    hostname: airflow
    ports:
      - "8080:8080"
    command: standalone
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    environment:
      - PYTHONPATH=/opt/airflow/dags
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://${MYAPP_DB_USER}:${MYAPP_DB_PASSWORD}@${MYAPP_DB_DOCKER_HOST}:${MYAPP_DB_PORT}/${MYAPP_DB_DATABASE}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    env_file:
      - .env